import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import Header from "@/components/Header";
import { Noto_Sans_Lao } from "next/font/google";

const inter = Noto_Sans_Lao({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <Header />
          <div className='flex flex-col min-h-screen max-w-4xl mx-auto'>
            <div className='flex-grow mt-20'>{children}</div>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
